### ISSUE TITLE
dsemver not runs with dmd 2.097.0

### ISSUE THREAD

**Issue by Zardoz89** [symmetryinvestments/dsemver#12]
```
dub run dsemver@ -- -h
Fetching dsemver ~master...
Building package dsemver in /home/luis/.dub/packages/dsemver-master/dsemver/
Performing "debug" build using /usr/bin/dmd for x86_64.
argsd 1.0.0: target for configuration "library" is up to date.
dsemver ~master: building configuration "application"...
../../../.dub/packages/dsemver-master/dsemver/source/dsemver/compare.d(120,2): Error: invalid `foreach` aggregate `old.members`, define `opApply()`, range primitives, or use `.tupleof`
/usr/bin/dmd failed with exit code 1.
```

**Comment by burner** [comment]
Thank you

**Comment by burner** [comment]
https://github.com/symmetryinvestments/dsemver/releases/tag/v1.2.2 should work with 2.097 

if not please reopen.
